site:
  name: 理科迷
  site: 'https://LKM-2014.github.io'
  base: '/LKM-official-website'
  trailingSlash: false

  googleSiteVerificationId: null

# Default SEO metadata
metadata:
  title:
    default: 理科迷
    template: '%s — LKM'
  description: '理科迷 (LKM) — 创立于 2014 年的科技爱好者社区。覆盖数学、物理、化学、生物、信息技术等多个学科，由普罗大众组成，让科学回归每一个人。'
  robots:
    index: true
    follow: true
  openGraph:
    site_name: LKM
    images:
      - url: '~/assets/images/default.png'
        width: 1200
        height: 628
    type: website
  twitter:
    handle: '@lkm'
    site: '@lkm'
    cardType: summary_large_image

i18n:
  language: zh-cn
  textDirection: ltr

apps:
  blog:
    isEnabled: true
    postsPerPage: 6

    post:
      isEnabled: true
      permalink: '/%slug%'
      robots:
        index: true

    list:
      isEnabled: true
      pathname: 'blog'
      robots:
        index: true

    category:
      isEnabled: true
      pathname: 'category'
      robots:
        index: true

    tag:
      isEnabled: true
      pathname: 'tag'
      robots:
        index: false

    isRelatedPostsEnabled: true
    relatedPostsCount: 4

analytics:
  vendors:
    googleAnalytics:
      id: null

ui:
  theme: 'system'
